src/models/StockMovement.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace quoma\products\models;

use Yii;
use \frontend\models\Website;
use frontend\modules\websiteConfig\models\WebsiteConfig;
use \frontend\models\Cart;
use \common\components\helpers\CheckoutHelper;

/**
 * This is the model class for table "stock_movement".
 *
 * @property int $stock_movement_id
 * @property string $type
 * @property string $concept
 * @property double $qty
 * @property int $create_at
 * @property string $date
 * @property string $time
 * @property double $stock
 * @property double $avaible_stock
 * @property int $product_id
 * @property int $active
 * @property string $expiration
 * @property string $expiration_timestamp
 * @property int $website_id
 *
 * @property Product $product
 */
class StockMovement extends \quoma\core\db\ActiveRecord 
{

    /**
     * TODO: Implementar Stock Secundario
     * * */
    const enable_secondary_stock = false;

    public function __construct($config = array()) {

        $from = get_called_class();

        if (!in_array($from, [
                    'quoma\products\models\search\StockMovementSearch',
                    'quoma\products\components\StockExpert'
                ]))
            ;

        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'stock_movement';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb() {
        return Yii::$app->get('db_product');
    }
    
    /**
     * Datos iniciales
     */
    public function init() {
        $this->active = 1;
        parent::init();
    }

    public function behaviors() {
        return [
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['create_at'],
                ],
            ],
            'date' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['date'],
                ],
                'value' => function() {
                    return date('Y-m-d');
                },
            ],
            'time' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['time'],
                ],
                'value' => function() {
            return date('h:i');
        },
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        $rules = [
            [['type', 'qty'], 'required'],
            [['create_at', 'product_id','website_id'], 'integer'],
            [['date', 'time','website', 'expiration','expiration_timestamp'], 'safe'],
            [['product_id'], 'required'],
            [['concept'], 'string', 'max' => 255],
        ];

        if (!empty($this->product)) {

            $unit = $this->product->unit;

            if ($unit->type == 'int')
                $rules[] = [['qty', 'stock', 'avaible_stock'], 'integer'];
            else
                $rules[] = [['qty', 'stock', 'avaible_stock'], 'number'];

            $secondaryUnit = $this->product->secondaryUnit;

            //Secondary stock
            if (WebsiteConfig::getWebsiteConfig('enable_secondary_stock', $this->website_id)->value && $secondaryUnit) {

                if ($secondaryUnit->type == 'int')
                    $rules[] = [['secondary_qty', 'secondary_stock', 'secondary_avaible_stock'], 'integer'];
                else
                    $rules[] = [['secondary_qty', 'secondary_stock', 'secondary_avaible_stock'], 'number'];
            }
        }else {
            $rules[] = [['qty', 'stock', 'avaible_stock'], 'number'];
            if (WebsiteConfig::getWebsiteConfig('enable_secondary_stock', $this->website_id)->value
                && $this->product
                && $this->product->secondaryUnit) {
                $rules[] = [['secondary_qty', 'secondary_stock', 'secondary_avaible_stock'], 'number'];
            }
        }

        return $rules;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'stock_movement_id' => Yii::t('product', 'Stock Movement ID'),
            'type' => Yii::t('product', 'Type'),
            'concept' => Yii::t('product', 'Concept'),
            'qty' => Yii::t('product', 'Quantity'),
            'qtyAndUnit' => Yii::t('product', 'Quantity'),
            'secondary_qty' => Yii::t('product', 'Secondary Quantity'),
            'secondaryQtyAndUnit' => Yii::t('product', 'Secondary Quantity'),
            'create_at' => Yii::t('product', 'Create Timestamp'),
            'date' => Yii::t('product', 'Date'),
            'time' => Yii::t('product', 'Time'),
            'stock' => Yii::t('product', 'Stock'),
            'avaible_stock' => Yii::t('product', 'Avaible Stock'),
            'secondary_stock' => Yii::t('product', 'Secondary Stock'),
            'secondary_avaible_stock' => Yii::t('product', 'Avaible Secondary Stock'),
            'product_id' => Yii::t('product', 'Product'),
            'company' => Yii::t('product', 'Company')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct() {
        return $this->hasOne(Product::className(), ['product_id' => 'product_id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWebsite() {
        return $this->hasOne(Website::className(), ['website_id' => 'website_id']);
    }

        /**
     * @return \yii\db\ActiveQuery
     */
    public function getCart() {
        return $this->hasOne(Cart::className(), ['cart_id' => 'cart_id']);
    }
    

    /**
     * Devuelve el color asociado al producto en formato RGB
     * @return string
     */
    public function getRgb() {

        return $this->product->rgb;
    }

    public function getDeletable() {

        return false;
    }

    /**
     * Actualizamos valores
     * @param type $insert
     * @param type $changedAttributes
     */
    public function afterSave($insert, $changedAttributes) {


        //seteo timestamp de expiración
        if ($this->type == 'r_out') {
            $expiration_config = WebsiteConfig::getWebsiteConfig('reservation_expiration', $this->website_id)->value;
            $this->expiration = date('Y-m-d', strtotime("+ $expiration_config minutes"));
            $this->expiration_timestamp = strtotime("+$expiration_config minutes", time());
            $this->updateAttributes(['expiration','expiration_timestamp']);
        }

        if ($this->type == 'in') {
            $this->product->updateAttributes([
                'balance' => $this->product->balance + $this->qty,
                'secondary_balance' => $this->product->secondary_balance + $this->secondary_qty,
            ]);
        } elseif ($this->type == 'out') {
            $this->product->updateAttributes([
                'balance' => $this->product->balance - $this->qty,
                'secondary_balance' => $this->product->secondary_balance - $this->secondary_qty,
            ]);
        }

        parent::afterSave($insert, $changedAttributes);
    }

    //Devuelve el balance a la fecha del movimiento de stock actual
    public function getBalance($website = null, $secondary = false) {
        //Stock principal o secundario?
        $qty_attr = 'qty';
        if ($secondary) {
            $qty_attr = 'secondary_qty';
        }

        $in = StockMovement::find()->where([
                    'active' => 1,
                    'product_id' => $this->product_id,
                    'type' => 'in'
                ])->andWhere('stock_movement_id<=' . $this->stock_movement_id);

        $out = StockMovement::find()->where([
            'active' => 1,
            'product_id' => $this->product_id,
            'type' => 'out'
        ]);

        if ($company) {
            $in->andWhere(['website_id' => $website->website_id]);
            $out->andWhere(['website_id' => $website->website_id]);
        }

        return $in->sum($qty_attr) - $out->sum($qty_attr);
    }

    public function getSecondaryBalance($website = null) {
        return $this->getBalance($website, true);
    }

    /**
     * Devuelve la cantidad con la unidad
     * @return string
     */
    public function getQtyAndUnit() {
        if ($this->product->unit->symbol_position == 'prefix') {
            return $this->product->unit->symbol . " $this->qty";
        } else {
            return "$this->qty" . $this->product->unit->symbol;
        }
    }

    /**
     * Devuelve la cantidad con la unidad
     * @return string
     */
    public function getSecondaryQtyAndUnit() {
        if (!$this->secondary_qty) {
            return null;
        }

        if ($this->product->secondary_unit_id && $this->product->secondaryUnit->symbol_position == 'prefix') {
            return $this->product->secondaryUnit->symbol . " $this->secondary_qty";
        } elseif ($this->product->secondary_unit_id) {
            return $this->secondary_qty . $this->product->secondaryUnit->symbol;
        }

        return null;
    }

    /**
     * Devuelve la cantidad con la unidad
     * @return string
     */
    public function getStockAndUnit() {
        if ($this->product->unit->symbol_position == 'prefix') {
            return $this->product->unit->symbol . " $this->stock";
        } else {
            return "$this->stock" . $this->product->unit->symbol;
        }
    }

    /**
     * Devuelve la cantidad con la unidad
     * @return string
     */
    public function getSecondaryStockAndUnit() {

src/controllers/ProductController.php
<?php

namespace quoma\products\controllers;

use Yii;
use quoma\products\models\Product;
use quoma\products\models\search\ProductSearch;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends \quoma\products\components\Controller {
     
    protected function setWebsite($website)
    {
        $this->website = $website;
    }

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }
   
    /**
     * Lists all Product models.
     * @return mixed
     */
    public function actionIndex() {

        $searchModel = new ProductSearch();
        
        $searchModel->website_id = $this->website->website_id;

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Product model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
         $model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Product model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {

        $model = new Product();
        $price = new \quoma\products\models\ProductPrice();
        
        $model->website_id = $this->website->website_id;
        $price->website_id = $this->website->website_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if(isset(Yii::$app->request->post()['ProductPrice'])){
                $model->savePrices(Yii::$app->request->post()['ProductPrice']);
            }

            return $this->redirect(['view', 'id' => $model->product_id]);
        } else {
            $products = ArrayHelper::map(Product::find()->andWhere(['status' => 'enabled', 'website_id' => $this->website->website_id])->all(), 'product_id', 'name');

            return $this->render('create', [
                'model' => $model,
                'price' => $price,
                'products' => $products
            ]);
        }
    }

    /**
     * Updates an existing Product model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $price = new \quoma\products\models\ProductPrice();
     
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->unlinkAll('productPrices',true);
            $model->savePrices(Yii::$app->request->post()['ProductPrice']);
            return $this->redirect(['view', 'id' => $model->product_id]);
        } else {
            $products = ArrayHelper::map(Product::find()->andWhere(['status' => 'enabled', 'website_id' => $this->website->website_id])->all(), 'product_id', 'name');

            return $this->render('update', [
                'model' => $model,
                'price' => $price,
                'products' => $products
            ]);
        }
    }

    /**
     * Deletes an existing Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $model = $this->findModel($id);
        
        $model->unlinkAll('productPrices',true);
        $model->unlinkAll('categories',true);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Product model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Product the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Product::findOne($id)) !== null) {

            if($model->website_id != $this->website->website_id){
                throw new NotFoundHttpException('The requested page does not exist.');
            }

            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

src/controllers/StockMovementController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace quoma\products\controllers;

use Yii;
use quoma\products\models\StockMovement;
use quoma\products\models\search\StockMovementSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use quoma\products\models\Product;

/**
 * Description of StockMovement
 *
 * @author Gabriela
 */
class StockMovementController extends \quoma\products\components\Controller 
{
      protected function setWebsite($website)
    {
        $this->website = $website;
    }

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Creates a new StockMovement model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($product_id, $type = 'in')
    {
        $model = Yii::$app->getModule('product')->stock->createMove();

        $product = Product::findOne($product_id);
        $model->website_id = $this->website->website_id;
        if($product === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        if($type !== null)
            $model->type = $type;
        
        $model->product_id = $product->product_id;
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->stock_movement_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    
     /**
     * Finds the StockMovement model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return StockMovement the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StockMovement::findOne($id)) !== null) {

            if($model->website_id != $this->website->website_id){
                throw new NotFoundHttpException('The requested page does not exist.');
            }
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
}

src/views/stock-movement/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\modules\websiteConfig\models\WebsiteConfig;
use quoma\products\components\StockInput;

/**
 * @var yii\web\View $this
 * @var app\modules\sale\models\StockMovement $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="stock-movement-form">

    <?php $form = ActiveForm::begin(); ?>
    

    <?= $form->field($model, 'type')->radioList(['in'=>quoma\products\ProductsModule::t('In'),'out'=>quoma\products\ProductsModule::t('Out')]) ?>

    <div class="row">
        <div class="col-sm-3">
            
            <?= $form->field($model, 'qty')->widget(\quoma\products\components\StockInput::className(),[
                'unit' => $model->product->unit
            ]) ?>

            <?php
            $config_secundary_stock = WebsiteConfig::getWebsiteConfig('enable_secondary_stock', $model->product->website_id);
            if($config_secundary_stock->value && $model->product->secondaryUnit): ?>
                <?= $form->field($model, 'secondary_qty')->widget(StockInput::className(),[
                    'unit' => $model->product->secondaryUnit
                ]) ?>
            <?php endif; ?>
            
        </div>
    </div>
    
    <?= $form->field($model, 'concept')->textInput(['maxlength' => 255]) ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? quoma\products\ProductsModule::t( 'Create') : quoma\products\ProductsModule::t('Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/stock-movement/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\modules\sale\models\StockMovement $model
 */

$this->title = quoma\products\ProductsModule::t('Create') . ' '. quoma\products\ProductsModule::t('Stock Movement');
$this->params['breadcrumbs'][] = ['label' => quoma\products\ProductsModule::t( 'Stock Movement'), 'url' => ['product/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="stock-movement-create">
	<!-- TO DO: ver si esta bien esta vista -->

        <h1><?= Html::encode($this->title) ?></h1>

        <h4><?= quoma\products\ProductsModule::t('Product') ?>: <?= $model->product->name; ?> #<?= $model->product->code; ?></h4>
        <hr/>
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>

        <hr/>
        <h4 class="pull-right"><?= quoma\products\ProductsModule::t('Product') ?>: <?= $model->product->name; ?> #<?= $model->product->code; ?></h4>

</div>

src/views/stock-movement/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use frontend\modules\websiteConfig\models\WebsiteConfig;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = quoma\products\ProductsModule::t('Stock Movements');
$this->params['breadcrumbs'][] = $this->title;

$website = $this->context->website;

?>
<div class="product-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    $values = [
        'in' => '<span style="color: green;" class="glyphicon glyphicon-arrow-up"></span> '. quoma\products\ProductsModule::t('In'),
        'out' => '<span style="color: red;" class="glyphicon glyphicon-arrow-down"></span> '. quoma\products\ProductsModule::t('Out'),
        'r_in' => '<span style="color: gold;" class="glyphicon glyphicon-arrow-down"></span> '. quoma\products\ProductsModule::t('R. In'),
        'r_out' => '<span style="color: orange;" class="glyphicon glyphicon-arrow-down"></span> '. quoma\products\ProductsModule::t('R. Out')
    ];

    ?>


    <!-- <p> -->
    <div class="row">
        <div class="col-sm-12">
            <form class="form-inline" role="form">

                <div class="form-group col-md-2">
                    <?= Html::activeLabel($searchModel, 'fromDate', ['class'=>'sr-only']); ?>
                    <?php
                    echo yii\jui\DatePicker::widget([
                        'language' => Yii::$app->language,
                        'model' => $searchModel,
                        'attribute' => 'fromDate',
                        'dateFormat' => 'dd-MM-yyyy',
                        'options'=>[
                            'class'=>'form-control filter dates',
                            'placeholder'=>quoma\products\ProductsModule::t('From Date')
                        ]
                    ]);
                    ?>
                    <?php //Html::activeTextInput($searchModel, 'fromDate', ['class'=>'form-control filter','placeholder'=>Yii::t('app','From Date')]); ?>
                </div>
                <div class="form-group col-md-2">
                    <?= Html::activeLabel($searchModel, 'toDate', ['class'=>'sr-only']); ?>
                    <?php
                    echo yii\jui\DatePicker::widget([
                        'language' => Yii::$app->language,
                        'model' => $searchModel,
                        'attribute' => 'toDate',
                        'dateFormat' => 'dd-MM-yyyy',
                        'options'=>[
                            'class'=>'form-control filter dates',
                            'placeholder'=>quoma\products\ProductsModule::t('To Date')
                        ]
                    ]);
                    ?>
                    <?php // Html::activeTextInput($searchModel, 'toDate', ['class'=>'form-control filter','placeholder'=>Yii::t('app','To Date')]); ?>
                </div>
                <div class="form-group col-md-2 no-padding">
                    <div onclick="Search.clearDates();" class="btn btn-warning float-right"><span class="glyphicon glyphicon-remove"></span> <?= quoma\products\ProductsModule::t('Clean dates'); ?></div>
                </div>
            </form>
        </div>
    </div>

    <div class="clearfix"><br></div>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterSelector' => '.filter',
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'type',
                'value' => function($data) use ($values){ return $values[$data->type];} ,
                'format' => ['html'],
                'filter' =>[
                    'in' => quoma\products\ProductsModule::t('In'),
                        'out' => quoma\products\ProductsModule::t('Out'),
                        'r_out' => quoma\products\ProductsModule::t('R. Out')
                    ]
            ],
            [
                    'attribute' => 'product_id',
                    'value' => function($data){ return "<a href='".Url::to(['/unique/unique-product/product/view', 'id' => $data->product_id])."'>".$data->product->name."</a>";},
                    'format' => 'raw'
            ],
            'qtyAndUnit',
            [
                'attribute' => 'secondaryQtyAndUnit',
                'visible'=> WebsiteConfig::getWebsiteConfig('enable_secondary_stock', $website->website_id)->value
            ],
            'concept',
            [
                'attribute'=>'create_at',
                'value' => function($data){ return date('d-m-Y h:i:s',$data->create_at);},
            ],
           ['class' => 'common\components\grid\ActionColumn',
               'template' => '{view}'],
        ],
    ]); ?>
</div>


<script type="text/javascript">

    var Search = new function(){

        //public
        this.windowKeypress = function(e){

            if($(":focus").length == 0 && e.which > 20 && e.which < 127) {

                autoFocus = true;

                $("#search_text").val(String.fromCharCode( e.which ));
                $("#search_text").focus();

            }

        }
        this.clear = function(){

            $.pjax({container: '#grid', url: '<?= yii\helpers\Url::toRoute(['stock-movement/graph']) ?>'});

        }

        this.clearDates = function(){

            $('.dates').val('');
            $('.dates').change();

        }

    }

</script>

src/views/stock-movement/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use frontend\modules\websiteConfig\models\WebsiteConfig;

/**
 * @var yii\web\View $this
 * @var app\modules\sale\models\StockMovement $model
 */

$this->title = $model->product->name;
$this->params['breadcrumbs'][] = ['label' => quoma\products\ProductsModule::t('Stock movements'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="stock-movement-view">

    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>    

    <?php 
    $values = [
        'in' => '<span style="color: green;" class="glyphicon glyphicon-arrow-up"></span> '. quoma\products\ProductsModule::t('In'),
        'out' => '<span style="color: red;" class="glyphicon glyphicon-arrow-down"></span> '. quoma\products\ProductsModule::t('Out'),
        'r_in' => '<span style="color: gold;" class="glyphicon glyphicon-arrow-down"></span> '. quoma\products\ProductsModule::t('R. In'),
        'r_out' => '<span style="color: orange;" class="glyphicon glyphicon-arrow-down"></span> '. quoma\products\ProductsModule::t('R. Out')
    ];
    
    ?>
    
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'stock_movement_id',
            [
                'attribute' => 'type',
                'value' => $values[$model->type],
                'format' => ['html']
            ],
            'qtyAndUnit',
            [
                'attribute' => 'secondaryQtyAndUnit',
                'visible'=> WebsiteConfig::getWebsiteConfig('enable_secondary_stock', $model->product->website_id)->value
            ],
            'concept',
            [
                'attribute'=>'date',
                'format'=>['date','dd-MM-Y']
            ],
            'time',
        ],
    ]) ?>

</div>